import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // ⚡ SIMULATE SERVER FETCH (e.g. database query or session retrieval)
  // In a real application, you would do: const user = await db.getUser()
  const mockServerFetchedUser = "Mojahed Mohammed Hussien";
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* We seed the store with the server-fetched user name */}
        <StoreProvider initialState={{ username: mockServerFetchedUser }}>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
